# Generated by Django 2.1.7 on 2019-05-30 08:17

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('datei', models.FileField(upload_to='')),
                ('hochlader', models.CharField(max_length=100)),
                ('freie_beschreibung', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('art', models.CharField(choices=[('Behoerde', 'Behoerde'), ('Firma', 'Firma'), ('Institut', 'Institut'), ('Verband', 'Verband')], max_length=50, null=True)),
                ('freie_beschreibung', models.TextField(blank=True, null=True)),
                ('strasse', models.CharField(max_length=100)),
                ('hausnummer', models.IntegerField()),
                ('hausnummerzusatz', models.CharField(blank=True, max_length=10, null=True)),
                ('plz', models.IntegerField()),
                ('ort', models.CharField(max_length=50)),
                ('bundesland', models.CharField(choices=[('BB', 'Brandenburg'), ('BE', 'Berlin'), ('BW', 'Baden-Wuerttemberg'), ('BY', 'Bayern'), ('HB', 'Bremen'), ('HE', 'Hessen'), ('HH', 'Hamburg'), ('MV', 'Mecklenburg-Vorpommern'), ('NI', 'Niedersachsen'), ('NW', 'Nordrhein-Westfalen'), ('RP', 'Rheinland-Pfalz'), ('SH', 'Schleswig-Holstein'), ('SL', 'Saarland'), ('SN', 'Sachsen'), ('ST', 'Sachsen-Anhalt'), ('TH', 'Thueringen')], max_length=2)),
                ('land', models.CharField(max_length=50)),
                ('xKoordinate', models.FloatField(blank=True, null=True)),
                ('yKoordinate', models.FloatField(blank=True, null=True)),
                ('bereich', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Agrarwirtschaft', 'Agrarwirtschaft'), ('CAD', 'CAD'), ('Geo- und Landschaftsökologie', 'Geo- & Landschaftsökologie'), ('Geodäse und Vermessung', 'Geodäse und Vermessung'), ('Geodaten', 'Geodaten'), ('Geographie', 'Geographie'), ('Geoinformatik', 'Geoinformatik'), ('Geologie', 'Geologie'), ('Geomarketing', 'Geomarketing'), ('Geophysik', 'Geophysik'), ('Geowissenschaften', 'Geowissenschaften'), ('GIS', 'GIS'), ('GIS-Applikation', 'GIS-Applikation'), ('Hydrologie und Wasserbau', 'Hydrologie und Wasserbau'), ('Kartographie und Visualisierung', 'Kartographie und Visualisierung'), ('Meteorologie', 'Meteorologie'), ('Navigation und Telematik', 'Navigation und Telematik'), ('Photogrammetrie', 'Photogrammetrie'), ('Planung', 'Planung'), ('Raumordnung', 'Raumordnung'), ('Software-Entwicklung', 'Software-Entwicklung'), ('Umwelt- und Naturschutz', 'Umwelt- und Naturschutz'), ('Verkehr', 'Verkehr'), ('Vermessung', 'Vermessung')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KontaktFirma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=50)),
                ('nachname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('freie_beschreibung', models.TextField(blank=True, null=True)),
                ('firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Firma')),
            ],
        ),
        migrations.CreateModel(
            name='MitarbeiterUni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=50)),
                ('nachname', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Protokoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField()),
                ('verfasser', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('kontaktfirma', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='crm.KontaktFirma')),
            ],
        ),
        migrations.AddField(
            model_name='dokument',
            name='firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Firma'),
        ),
        migrations.AddField(
            model_name='dokument',
            name='kontaktfirma',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='crm.KontaktFirma'),
        ),
    ]
