# Generated by Django 2.2.1 on 2019-06-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dokument',
            options={'verbose_name_plural': 'Dokumente'},
        ),
        migrations.AlterModelOptions(
            name='firma',
            options={'verbose_name_plural': 'Firmen'},
        ),
        migrations.AlterModelOptions(
            name='kontaktfirma',
            options={'verbose_name_plural': 'Kontakt Firmen'},
        ),
        migrations.AlterModelOptions(
            name='mitarbeiteruni',
            options={'verbose_name_plural': 'Mitarbeiter Uni'},
        ),
        migrations.AlterModelOptions(
            name='protokoll',
            options={'verbose_name_plural': 'Protokolle'},
        ),
        migrations.AddField(
            model_name='kontaktfirma',
            name='telefon',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
