# Generated by Django 2.0.13 on 2019-06-18 20:02

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_kontaktfirma_telefon2'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontaktfirma',
            name='xy',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Bacherlorarbeit', 'Bacherlorarbeit'), ('Masterarbeit', 'Masterarbeit'), ('Praktikum', 'Praktikum'), ('Exkursion', 'Exkursion')], max_length=200, null=True),
        ),
    ]
