# Generated by Django 2.0.13 on 2019-06-18 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_kontaktfirma_xy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kontaktfirma',
            old_name='xy',
            new_name='befaehigung',
        ),
    ]
