# Generated by Django 2.0.13 on 2019-06-18 21:35

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20190618_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kontaktfirma',
            name='befaehigung',
        ),
        migrations.AddField(
            model_name='firma',
            name='befaehigung',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Bacherlorarbeit', 'Bacherlorarbeit'), ('Masterarbeit', 'Masterarbeit'), ('Praktikum', 'Praktikum'), ('Exkursion', 'Exkursion')], max_length=200, null=True),
        ),
    ]
