# Generated by Django 2.0.13 on 2019-06-26 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0006_auto_20190618_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontaktfirma',
            name='mitarbeiter_uni',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
