# Generated by Django 2.0.13 on 2019-06-27 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20190626_2256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MitarbeiterUni',
        ),
    ]
