# Generated by Django 2.0.13 on 2019-06-28 08:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_delete_mitarbeiteruni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='befaehigung',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Bachelorarbeit', 'Bachelorarbeit'), ('Masterarbeit', 'Masterarbeit'), ('Praktikum', 'Praktikum'), ('Exkursion', 'Exkursion')], max_length=200, null=True),
        ),
    ]
